### ISSUE TITLE
On mobile, zooming in/out will zoom in/out on browser too

### ISSUE THREAD

**Issue by jtsimoes** [Raruto/leaflet-gesture-handling#11]
Hi @Raruto. Great job maintaining this plugin!

I am having some issues on mobile, when zooming in or out with two fingers. It's activating the zoom on the browser too.

Can you check this please? On the [original fork](https://github.com/elmarquis/Leaflet.GestureHandling), this doesn't seem to happen.

I'm using the latest stable version of Leaflet (1.7.1) with the latest Chrome version on an Android phone.

Thanks!

**Comment by jtsimoes** [comment]
Btw, I have the same problem in your [demo](https://raruto.github.io/leaflet-gesture-handling/examples/leaflet-gesture-handling.html) too.

On PC, everything is working just fine, the browser's zoom is not affected by the CTRL + mouse wheel.

**Comment by Raruto** [comment]
Hi João Tomás,
maybe ironic but I don't have a touch device, since we are not talking about a huge library maybe it's better that you do the tests yourself... 😄 (It has also been a while since I developed this library, not least because it is quite stable and it doesn't require so many frequent updates)

If it helps, these are some functions you can start checking:

https://github.com/Raruto/leaflet-gesture-handling/blob/624204c84172b4ae565b113d9670c1801978e8ae/src/index.js#L21

https://github.com/Raruto/leaflet-gesture-handling/blob/624204c84172b4ae565b113d9670c1801978e8ae/src/index.js#L83-L93

https://github.com/Raruto/leaflet-gesture-handling/blob/624204c84172b4ae565b113d9670c1801978e8ae/src/index.js#L23-L28

https://github.com/Raruto/leaflet-gesture-handling/blob/624204c84172b4ae565b113d9670c1801978e8ae/src/index.js#L175-L211

_Have nice day,
Raruto_

**Comment by jtsimoes** [comment]
Okay, I think I figure it out. Looks like it's a simple missing `e.preventDefault();` on conditional code block at line 514.

See https://github.com/jtsimoes/leaflet-gesture-handling/commit/b5119ccd3d1db1470b104237c840dc39b4772a84

**Comment by Raruto** [comment]
Ok, feel free to make a pull request.

For those who like to read the explanation is here: https://github.com/elmarquis/Leaflet.GestureHandling/issues/65#issuecomment-848183913

**Comment by jtsimoes** [comment]
You can change it yourself, no problem!

I wish I had seen that earlier 😂
