### ISSUE TITLE
Quick tip to keep the demo always up to date effortlessly

### ISSUE THREAD

**Issue by jtsimoes** [Raruto/leaflet-gesture-handling#13]
Hi again @Raruto!

Not sure if you already know this, but you can write the source of the script/link from CDN with `@latest` instead of `@1.4.1` or other version number. Like so:

```html
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-gesture-handling@latest/dist/leaflet-gesture-handling.min.css">
<script src="https://unpkg.com/@raruto/leaflet-gesture-handling@latest/dist/leaflet-gesture-handling.min.js"></script>
```

With `@latest`, the CDN will always redirect to the latest version of the plugin (1.4.1 currently).

This way, you don't need to update the demo all the time, like you did on the commit 83aa537eecf31521274091678b84eebdcab55dda, for example.

Hope it helps!

**Comment by Raruto** [comment]
Hi João Tomás,

```html
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-gesture-handling@latest/dist/leaflet-gesture-handling.min.css">
<script src="https://unpkg.com/@raruto/leaflet-gesture-handling@latest/dist/leaflet-gesture-handling.min.js"></script>
```

that's right, it's also mentioned in the readme file: https://github.com/Raruto/leaflet-gesture-handling#how-to-use, but if you are in a production environment I would recommend doing more as follows:

```html
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-gesture-handling@1.4.x/dist/leaflet-gesture-handling.min.css">
<script src="https://unpkg.com/@raruto/leaflet-gesture-handling@1.4.x/dist/leaflet-gesture-handling.min.js"></script>
```

I don't usually use that in my plugin examples because a lot of people just copy and paste (without really understanding the code) and then complain that subsequent version upgrades broke something. There may be smarter ways of doing this, but so I'm always forced to check that all the demos here on github are bug-free.

_Have a nice day,
Raruto_

**Comment by jtsimoes** [comment]
Oh, oops... Didn't see that on the README 🤐

That makes a lot of sense, nice attention to detail.
You have a point, thanks for enlightening me!
