### ISSUE TITLE
What's the difference...

### ISSUE THREAD

**Issue by bryanbuchs** [Raruto/leaflet-gesture-handling#4]
How is your plugin different than @elmarquis/Leaflet.GestureHandling ? Is this a fork? Is there any new functionality it provides, or specific issues it addresses that the original doesn't?

Just trying to evaluate the two.

**Comment by Raruto** [comment]
Hi Bryan,

I found myself maintaining this repository due to the lack of support of its original author (https://github.com/elmarquis/Leaflet.GestureHandling/pull/43).

Taking a quick look at the fading behavior of these two examples, it should be quite clear:

- https://raruto.github.io/leaflet-gesture-handling/examples/leaflet-gesture-handling.html
- https://elmarquis.github.io/Leaflet.GestureHandling/examples/
